export const USER_INFO_FAILED = "USER_INFO_FAILED";
export const USER_INFO_REQUEST = "USER_INFO_REQUEST";
export const USER_INFO_SUCCESS = "USER_INFO_SUCCESS";

export const USER_DESCRIPTION_FAILED = "USER_DESCRIPTION_FAILED";
export const USER_DESCRIPTION_REQUEST = "USER_DESCRIPTION_REQUEST";
export const USER_DESCRIPTION_SUCCESS = "USER_DESCRIPTION_SUCCESS";
